In [182]:
import numpy as np
import pandas as pd

ingr = ["Salade", "Tomate", "Oignon", "Fromage", "Viande", "Poivron"]
nbIngr = 6
totIngr = 14
maxIngr = 4
intCons = [14, 16]
nbDist = 1000

In [190]:
distributions = []

while len(distributions) < nbDist:
    gen = np.random.randint(maxIngr + 1, size=nbIngr)
    if gen.sum() >= intCons[0] and gen.sum() <= intCons[1]:
        distributions.append(gen)

dist_table = pd.DataFrame(distributions, columns=ingr)
dist_table.to_csv("ingredients.csv", index=False)
dist_table.head(20)

    Salade  Tomate  Oignon  Fromage  Viande  Poivron
0        0       4       3        2       3        4
1        3       4       2        3       1        1
2        2       4       2        3       0        4
3        3       3       0        3       2        4
4        2       2       0        4       4        3
5        4       2       3        3       1        3
6        3       3       4        1       0        3
7        4       2       4        1       1        2
8        1       2       3        3       3        3
9        3       2       1        3       2        3
10       3       2       4        3       4        0
11       4       3       3        0       2        4
12       0       4       2        2       2        4
13       0       3       1        4       3        4
14       3       3       3        1       4        2
15       1       4       2        0       4        4
16       3       3       0        3       3        2
17       3       2       3        2       1        3
18       4       4       0        2       2        3
19       3       3       0        1       3        4